plugins {
    id "com.android.application"
}

android {
    namespace "it.marukoshi.yuvomiwrapper"
    compileSdk 35

    defaultConfig {
        applicationId "it.marukoshi.yuvomiwrapper"
        minSdk 23
        targetSdk 34
        versionCode 2
        versionName "0.2.0"
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }
}
